import "@/styles/globals.css";

import { ThemeProvider } from "@/components/theme-provider";

import { type Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Algos, Visualized",
  description:
    "Visualized Algorithm portfolio site. Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const plex = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={plex.className}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
